### ISSUE TITLE
https://winstall.app/packs invalid json response error

### ISSUE THREAD

**Issue by nightkall** [MehediH/winstall#67]
I get `invalid json response body at https://api.winstall.app/packs reason: Unexpected token < in JSON at position 0` error at [https://winstall.app/packs](https://winstall.app/packs)

**Comment by MehediH** [comment]
Should be fixed now.

**Comment by illright** [comment]
@MehediH This still happens when I click the "View Packs" button from [home](https://winstall.app/) (at the bottom of the page). When I subsequently reload the Packs page, it loads fine
